In [57]:
import numpy as np                                  # "Scientific computing"
import scipy.stats as stats                         # Statistical tests

import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype

import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation
import altair as alt

In [58]:
ryanair = pd.read_csv('../scraping/ryanair.csv')
tuifly = pd.read_csv('../scraping/tuifly.csv')
transavia = pd.read_csv('../scraping/transaviaApi.csv')

# transavia data transform

In [59]:
depTime = transavia['DepartureDateTime'].apply(lambda i: i.split('T')[1])
transavia.loc[transavia.index, 'depTime'] = depTime

arrivalTime = transavia['ArrivalDateTime'].apply(lambda i: i.split('T')[1])
transavia.loc[transavia.index, 'arrivalTime'] = arrivalTime

departDate = transavia['DepartureDateTime'].apply(lambda i: i.split('T')[0])
transavia.loc[transavia.index, 'DepartureDateTime'] = departDate

arrivalDate = transavia['ArrivalDateTime'].apply(lambda i: i.split('T')[0])
transavia.loc[transavia.index, 'ArrivalDateTime'] = arrivalDate

In [60]:
transavia.head()

,outboundFlightId,DepartureDateTime,ArrivalDateTime,Airline,FlightNumber,DepartureAirport,ArrivalAirport,TotalPriceAllPassengers,TotalPriceOnePassenger,BaseFare,TaxSurcharge,CurrencyCode,ProductClass,Deeplink,ResultSet,depTime,arrivalTime
0,BRUHER20230401HV9209,2023-04-01,2023-04-01,HV,9209,BRU,HER,329.0,329.0,291.86,37.14,EUR,Basic,https://www.transavia.com/nl-NL/bookingtool/fl...,{'count': 9},06:35:00,11:00:00
1,BRUHER20230404HV9211,2023-04-04,2023-04-04,HV,9211,BRU,HER,225.0,225.0,187.86,37.14,EUR,Basic,https://www.transavia.com/nl-NL/bookingtool/fl...,{'count': 9},07:10:00,11:35:00
2,BRUHER20230408HV9209,2023-04-08,2023-04-08,HV,9209,BRU,HER,175.0,175.0,137.86,37.14,EUR,Basic,https://www.transavia.com/nl-NL/bookingtool/fl...,{'count': 9},06:35:00,11:00:00
3,BRUHER20230411HV9211,2023-04-11,2023-04-11,HV,9211,BRU,HER,146.0,146.0,108.86,37.14,EUR,Basic,https://www.transavia.com/nl-NL/bookingtool/fl...,{'count': 9},07:10:00,11:35:00
4,BRUHER20230415HV9209,2023-04-15,2023-04-15,HV,9209,BRU,HER,161.0,161.0,123.86,37.14,EUR,Basic,https://www.transavia.com/nl-NL/bookingtool/fl...,{'count': 9},06:35:00,11:00:00

In [61]:
transavia.rename(columns= {"FlightNumber":"flightNumber"},inplace=True)
transavia.rename(columns= {"DepartureAirport":"departAirportCode"},inplace=True)
transavia.rename(columns= {"ArrivalAirport":"arrivalAirportCode"},inplace=True)
transavia.rename(columns= {"DepartureDateTime":"departDate"},inplace=True)
transavia.rename(columns= {"ArrivalDateTime":"arrivalDate"},inplace=True)

In [62]:
transavia.drop(columns=["Deeplink","ProductClass", "ResultSet"], inplace=True,axis=1)

In [63]:
transavia.head()

,outboundFlightId,departDate,arrivalDate,Airline,flightNumber,departAirportCode,arrivalAirportCode,TotalPriceAllPassengers,TotalPriceOnePassenger,BaseFare,TaxSurcharge,CurrencyCode,depTime,arrivalTime
0,BRUHER20230401HV9209,2023-04-01,2023-04-01,HV,9209,BRU,HER,329.0,329.0,291.86,37.14,EUR,06:35:00,11:00:00
1,BRUHER20230404HV9211,2023-04-04,2023-04-04,HV,9211,BRU,HER,225.0,225.0,187.86,37.14,EUR,07:10:00,11:35:00
2,BRUHER20230408HV9209,2023-04-08,2023-04-08,HV,9209,BRU,HER,175.0,175.0,137.86,37.14,EUR,06:35:00,11:00:00
3,BRUHER20230411HV9211,2023-04-11,2023-04-11,HV,9211,BRU,HER,146.0,146.0,108.86,37.14,EUR,07:10:00,11:35:00
4,BRUHER20230415HV9209,2023-04-15,2023-04-15,HV,9209,BRU,HER,161.0,161.0,123.86,37.14,EUR,06:35:00,11:00:00